import "./globals.css"
import type { Metadata } from "next"
import { ThemeProvider } from "@/components/ThemeProvider"
import { ModeToggler } from "@/components/ModeToggler"
import { ProfileCard } from "@/components/ProfileCard"
import Link from "next/link"
import Navbar from "@/components/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="mx-auto max-w-xs md:max-w-2xl xl:max-w-5xl 2xl:max-w-7xl ">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className="grid-cols-3 gap-16 pt-4 md:grid bg">
            {/* Left side */}
            <div className="hidden flex-col md:flex md:pt-[4.5rem]">
              {/* Profile card */}
              <ProfileCard />
            </div>

            {/* Content side */}
            <div className="col-span-2 md:pt-[4.5rem]">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
