name: Docker Build and Push

on:
  push:
    branches:
      - main
      - pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: docker login --username derenserce --password ${{ secrets.GH_PAT }} ghcr.io


      - name: Build and push image
        run: |
          docker build -t ghcr.io/ds-disx/disx-frontend .
          docker tag ghcr.io/ds-disx/disx-frontend:latest ghcr.io/ds-disx/disx-frontend:latest .
          docker push ghcr.io/ds-disx/disx-frontend:latest 